Fix running Running "jshint:all" (jshint) task >> 3 files lint free.
Running "exec:test" (exec) task
[0m[0m
[0m  Ruler[0m
[0m    #constructor[0m
    [32m  ✅[0m[90m creates a new instance with the correct signature[0m
[0m    #onResize[0m
    [32m  ✅[0m[90m detects expansion[0m
    [32m  ✅[0m[90m detects multiple expansions[0m
    [32m  ✅[0m[90m detects collapse[0m
    [32m  ✅[0m[90m detects multiple collapses[0m
    [32m  ✅[0m[90m detects a collapse and an expansion[0m
    [32m  ✅[0m[90m detects an expansion and a collapse[0m
[0m  Observer[0m
[0m    #constructor[0m
    [32m  ✅[0m[90m creates a new instance with the correct signature[0m
    [32m  ✅[0m[90m parses descriptors[0m
    [32m  ✅[0m[90m defaults descriptors that are not given[0m
    [32m  ✅[0m[90m defaults context to current window[0m
[0m    #getStyle[0m
    [32m  ✅[0m[90m creates the correct default style[0m
    [32m  ✅[0m[90m passes through all descriptors[0m
[0m    #load[0m
    [32m  ✅[0m[90m finds a font and resolve the promise[0m
    [32m  ✅[0m[90m finds a font and resolve the promise in an iframe (context)[0m
    [32m  ✅[0m[90m finds a font and resolves the promise even though the @font-face rule is not in the CSSOM yet[0m
    [32m  ✅[0m[90m finds a font and resolve the promise even when the page is RTL[0m
    [32m  ✅[0m[90m finds a font with spaces in the name and resolve the promise[0m
    [32m  ✅[0m[90m loads a font with spaces and numbers in the name and resolve the promise[0m
    [31m  1) fails to find a font and reject the promise[0m
    [32m  ✅[0m[90m finds the font even if it is already loaded[0m
    [32m  ✅[0m[90m finds a font with a custom unicode range within ASCII[0m
    [32m  ✅[0m[90m finds a font with a custom unicode range outside ASCII (but within BMP)[0m
    [32m  ✅[0m[90m finds a font with a custom unicode range outside the BMP[0m
    [32m  ✅[0m[90m fails to find the font if it is available but does not contain the test string[0m[33m (50ms)[0m
    [36m  - finds a locally installed font[0m
    [36m  - finds a locally installed font with the same metrics as the a fallback font (on OS X)[0m
[0m    hasSafari10Bug[0m
    [32m  ✅[0m[90m returns false when the user agent is not WebKit[0m
    [32m  ✅[0m[90m returns true if the browser is an affected version of Safari 10[0m
    [32m  ✅[0m[90m returns true if the browser is an WebView with an affected version of Safari 10[0m
    [32m  ✅[0m[90m returns false in older versions of Safari[0m
    [32m  ✅[0m[90m returns false in newer versions of Safari[0m
[0m    hasWebKitFallbackBug[0m
    [32m  ✅[0m[90m returns false when the user agent is not WebKit[0m
    [32m  ✅[0m[90m returns false when the user agent is WebKit but the bug is not present[0m
    [32m  ✅[0m[90m returns true when the user agent is WebKit and the bug is present[0m
    [32m  ✅[0m[90m returns true when the user agent is WebKit and the bug is present in an old version[0m
    [32m  ✅[0m[90m caches the results[0m
[92m [0m[32m 34 passing[0m[90m (275ms)[0m
[36m [0m[36m 2 pending[0m
[31m  1 failing[0m
[0m  1) Observer
       #load
         fails to find a font and reject the promise:
[0m[31m     UnexpectedError:
expected 'A network error occurred.' to equal '50ms timeout exceeded'

-A network error occurred.
+50ms timeout exceeded
[0m[90m
      at file:///home/stein/Projects/fontfaceobserver/test/observer-test.js:269:11
      set the query parameter full-trace=true to see the full stack trace
[0m
>> TypeError: Cannot read properties of undefined (reading 'result')
>>     at /home/stein/Projects/fontfaceobserver/node_modules/mocha-headless-chrome/lib/cli.js:41:17
>>     at processTicksAndRejections (node:internal/process/task_queues:96:5)
>> Exited with code: 1.
>> Error executing child process: Error: Command failed: ./node_modules/.bin/mocha-headless-chrome -f test/index.html
>> TypeError: Cannot read properties of undefined (reading 'result')
>>     at /home/stein/Projects/fontfaceobserver/node_modules/mocha-headless-chrome/lib/cli.js:41:17
>>     at processTicksAndRejections (node:internal/process/task_queues:96:5)
Warning: Task "exec:test" failed. Use --force to continue.

Aborted due to warnings..